export const variables = {
  options_all: [
    "Individual",
    "Dataset",
    "Original dataset",
    "Region",
    "Population",
    "Chromosome",
    "Haploidy",
    "Start",
    "End",
    "Length",
    "SNPs",
    "Mean Post. Prob.",
    "Ancestry",
    "Admix. Pop. Variants",
    "Altai",
    "Chagyrskaya",
    "Denisova",
    "Vindija"
  ],

  continuousOptions: [
    "Time",
    "Latitude",
    "Longitude",
    "Mean Length (bp)",
    "Median Length (bp)",
    "Max Length (bp)",
    "Min Length (bp)",
    "N Fragments",
    "Sequence (bp)",
    "Anc Africa",
    "Anc America",
    "Anc East Asia",
    "Anc Europe",
    "Anc Oceania",
    "Anc South Asia",
  ],
  continuousOptionsShort: [
    "tim",
    "lat",
    "lon",
    "len_mea",
    "len_med",
    "len_max",
    "len_min",
    "nfr",
    "seq",
    "ancAFR",
    "ancAMR",
    "ancEAS",
    "ancEUR",
    "ancOCE",
    "ancSAS",
  ],
  mappingToShort: {
    Autosome: "A",
    X: "X",
    "X Prime": "Xprime",
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    "Non DAVC": "nonDAVC",
    Individual: "ind",
    Sex: "sex",
    Population: "pop",
    Region: "reg",
    Dataset: "dat",
    "Original dataset": "oda",
    Time: "tim",
    Latitude: "lat",
    Longitude: "lon",
    Chromosome: "chrom",
    Ancestry: "anc",
    "Mean Length (bp)": "len_mea",
    "Median Length (bp)": "len_med",
    "Max Length (bp)": "len_max",
    "Min Length (bp)": "len_min",
    "N Fragments": "nfr",
    "Sequence (bp)": "seq",
    "Anc Africa": "ancAFR",
    "Anc America": "ancAMR",
    "Anc East Asia": "ancEAS",
    "Anc Europe": "ancEUR",
    "Anc Oceania": "ancOCE",
    "Anc South Asia": "ancSAS",
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
    Europe: "EUR",
    MID: "MID",
    "South Asia": "SAS",
    Africa: "AFR",
    "East Asia": "EAS",
    America: "AMR",
    Oceania: "OCE",
    "Central Asia": "CAS",
    Global: "GLOB",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    Joined: "joined",
    Frequency: "freq",
    Shared: "shared",
    Private: "private",
  },
  mappingToLong: {
    A: "Autosome",
    X: "X",
    Xprime: "X Prime",
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    nonDAVC: "Non DAVC",
    ind: "Individual",
    sex: "Sex",
    pop: "Population",
    reg: "Region",
    dat: "Dataset",
    oda: "Original dataset",
    tim: "Time",
    lat: "Latitude",
    lon: "Longitude",
    chrom: "Chromosome",
    anc: "Ancestry",
    len_mea: "Mean Length (bp)",
    len_med: "Median Length (bp)",
    len_max: "Max Length (bp)",
    len_min: "Min Length (bp)",
    nfr: "N Fragments",
    seq: "Sequence (bp)",
    ancAFR: "Anc Africa",
    ancAMR: "Anc America",
    ancEAS: "Anc East Asia",
    ancEUR: "Anc Europe",
    ancOCE: "Anc Oceania",
    ancSAS: "Anc South Asia",
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
    EUR: "Europe",
    MID: "MID",
    SAS: "South Asia",
    AFR: "Africa",
    EAS: "East Asia",
    AMR: "America",
    OCE: "Oceania",
    CAS: "Central Asia",
    GLOB: "Global",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    joined: "Joined",
    freq: "Frequency",
    shared: "Shared",
    private: "Private",
  },
};
