
export const datasets = {
  options: [
    "DATA",
    "PDAT",
    "GNOM",
    "PGNO",
    "GENI",
    "PGEN",
    "1KGP",
    "HGDP",
    "SGDP",
    "VANU",
    "IGDP",
    "AYTA",
    "OFAR",
  ],
  mapping: {
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
  },
};

export const chrms_discrete = {
  options: ["Autosome", "X", "X Prime"],
  mapping: {
    Autosome: "A",
    X: "X",
    "X Prime": "Xprime",
  },
};

export const chrms_all = {
  options: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "X",
    "X Prime",
  ],
  mapping: {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    X: "X",
    "X Prime": "Xprime",
  },
};

export const ancestries = {
  options: [
    "All",
    "Ambiguous",
    "Denisova",
    "Neanderthal",
    "Altai",
    "Vindija",
    "Chagyrskaya",
    "AmbigNean",
    "Non DAVC",
  ],
  mapping: {
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    "Non DAVC": "nonDAVC",
  },
};

export const ancestries_noAll = {
  options: [
    "Ambiguous",
    "Denisova",
    "Neanderthal",
    "Altai",
    "Vindija",
    "Chagyrskaya",
    "AmbigNean",
    "Non DAVC",
  ],
  mapping: {
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    "Non DAVC": "nonDAVC",
  },
};

export const bin_marks = [
  { value: 0, label: "0" },
  { value: 25, label: "25" },
  { value: 50, label: "50" },
  { value: 75, label: "75" },
  { value: 100, label: "100" },
];

export const bandwidth_divisor_marks = [
  { value: 1, label: "Dense" },
  { value: 100, label: "Light" },
];

export const td_bandwidth_divisor_marks = [
  { value: 1, label: "Detailed" },
  { value: 50, label: "Smooth" },
];


export const td_threshold_divisor_marks = [
  { value: 10, label: "Less" },
  { value: 45, label: "More" },
];

export const map_jit_marks = [
  { value: 0, label: "0" },
  { value: 1, label: "" },
  { value: 2, label: "" },
  { value: 3, label: "" },
  { value: 4, label: "" },
  { value: 5, label: "5" },
  { value: 6, label: "" },
  { value: 7, label: "" },
  { value: 8, label: "" },
  { value: 9, label: "" },
  { value: 10, label: "10" },
];

export const axis = { options: ["Free Axis", "Shared Axis", "Define Range"] };
export const color_chrms = {
  options: ["Ancestry", "Individual", "Mean Posterior Probability"],
};

export const mpp_marks = [
  { value: 0.5, label: "50%" },
  { value: 0.55, label: "" },
  { value: 0.6, label: "" },
  { value: 0.65, label: "65%" },
  { value: 0.7, label: "" },
  { value: 0.75, label: "" },
  { value: 0.8, label: "80%" },
  { value: 0.85, label: "" },
  { value: 0.9, label: "" },
  { value: 0.95, label: "95%" },
];
export const chr_range_marks = [
  { value: 0, label: "0" },
  { value: 5000, label: "" },
  { value: 10000, label: "" },
  { value: 15000, label: "" },
  { value: 20000, label: "" },
  { value: 25000, label: "" },
  { value: 30000, label: "" },
  { value: 35000, label: "" },
  { value: 40000, label: "" },
  { value: 45000, label: "" },
  { value: 50000, label: "50.000" },
  { value: 55000, label: "" },
  { value: 60000, label: "" },
  { value: 65000, label: "" },
  { value: 70000, label: "" },
  { value: 75000, label: "" },
  { value: 80000, label: "" },
  { value: 85000, label: "" },
  { value: 90000, label: "" },
  { value: 95000, label: "" },
  { value: 100000, label: "100.000" },
  { value: 105000, label: "" },
  { value: 110000, label: "" },
  { value: 115000, label: "" },
  { value: 120000, label: "" },
  { value: 125000, label: "" },
  { value: 130000, label: "" },
  { value: 135000, label: "" },
  { value: 140000, label: "" },
  { value: 145000, label: "" },
  { value: 150000, label: "150.000" },
  { value: 155000, label: "" },
  { value: 160000, label: "" },
  { value: 165000, label: "" },
  { value: 170000, label: "" },
  { value: 175000, label: "" },
  { value: 180000, label: "" },
  { value: 185000, label: "" },
  { value: 190000, label: "" },
  { value: 195000, label: "" },
  { value: 200000, label: "200.000" },
  { value: 205000, label: "" },
  { value: 210000, label: "" },
  { value: 215000, label: "" },
  { value: 220000, label: "" },
  { value: 225000, label: "" },
  { value: 230000, label: "" },
  { value: 235000, label: "" },
  { value: 240000, label: "" },
  { value: 245000, label: "" },
  { value: 250000, label: "250.000" },
];

export const min_chr_len_marks = [
  { value: 0, label: "0" },
  { value: 10, label: "" },
  { value: 20, label: "" },
  { value: 30, label: "" },
  { value: 40, label: "" },
  { value: 50, label: "" },
  { value: 60, label: "" },
  { value: 70, label: "" },
  { value: 80, label: "" },
  { value: 90, label: "" },
  { value: 100, label: "" },
  { value: 110, label: "" },
  { value: 120, label: "" },
  { value: 130, label: "" },
  { value: 140, label: "" },
  { value: 150, label: "" },
  { value: 160, label: "" },
  { value: 170, label: "" },
  { value: 180, label: "" },
  { value: 190, label: "" },
  { value: 200, label: "200" },
  { value: 210, label: "" },
  { value: 220, label: "" },
  { value: 230, label: "" },
  { value: 240, label: "" },
  { value: 250, label: "" },
  { value: 260, label: "" },
  { value: 270, label: "" },
  { value: 280, label: "" },
  { value: 290, label: "" },
  { value: 300, label: "" },
  { value: 310, label: "" },
  { value: 320, label: "" },
  { value: 330, label: "" },
  { value: 340, label: "" },
  { value: 350, label: "" },
  { value: 360, label: "" },
  { value: 370, label: "" },
  { value: 380, label: "" },
  { value: 390, label: "" },
  { value: 400, label: "400" },
  { value: 410, label: "" },
  { value: 420, label: "" },
  { value: 430, label: "" },
  { value: 440, label: "" },
  { value: 450, label: "" },
  { value: 460, label: "" },
  { value: 470, label: "" },
  { value: 480, label: "" },
  { value: 490, label: "" },
  { value: 500, label: "" },
  { value: 510, label: "" },
  { value: 520, label: "" },
  { value: 530, label: "" },
  { value: 540, label: "" },
  { value: 550, label: "" },
  { value: 560, label: "" },
  { value: 570, label: "" },
  { value: 580, label: "" },
  { value: 590, label: "" },
  { value: 600, label: "600" },
  { value: 610, label: "" },
  { value: 620, label: "" },
  { value: 630, label: "" },
  { value: 640, label: "" },
  { value: 650, label: "" },
  { value: 660, label: "" },
  { value: 670, label: "" },
  { value: 680, label: "" },
  { value: 690, label: "" },
  { value: 700, label: "" },
  { value: 710, label: "" },
  { value: 720, label: "" },
  { value: 730, label: "" },
  { value: 740, label: "" },
  { value: 750, label: "" },
  { value: 760, label: "" },
  { value: 770, label: "" },
  { value: 780, label: "" },
  { value: 790, label: "" },
  { value: 800, label: "800" },
  { value: 810, label: "" },
  { value: 820, label: "" },
  { value: 830, label: "" },
  { value: 840, label: "" },
  { value: 850, label: "" },
  { value: 860, label: "" },
  { value: 870, label: "" },
  { value: 880, label: "" },
  { value: 890, label: "" },
  { value: 900, label: "" },
  { value: 910, label: "" },
  { value: 920, label: "" },
  { value: 930, label: "" },
  { value: 940, label: "" },
  { value: 950, label: "" },
  { value: 960, label: "" },
  { value: 970, label: "" },
  { value: 980, label: "" },
  { value: 990, label: "" },
  { value: 1000, label: "1.000" },
];

export const regions = {
  options: [
    "Europe",
    "MID",
    "South Asia",
    "Africa",
    "East Asia",
    "America",
    "Oceania",
    "Central Asia",
  ],
  mapping: {
    Europe: "EUR",
    MID: "MID",
    "South Asia": "SAS",
    Africa: "AFR",
    "East Asia": "EAS",
    America: "AMR",
    Oceania: "OCE",
    "Central Asia": "CAS",
  },
};

export const regions_frag_vis_reg = {
  options: [
    "Europe",
    "MID",
    "South Asia",
    "Central Asia",
    "East Asia",
    "America",
    "Oceania",
    "Global",
  ],
};

export const ancestries_frag_vis_reg = {
  options: ["All", "Ambiguous", "Denisova", "Neanderthal", "Non DAVC"],
};

export const statistic_frag_vis_reg = {
  options: ["Joined", "Frequency", "Shared", "Private"],
};

export const variables = {
  options_all: [
    "Individual",
    "Sex",
    "Population",
    "Region",
    "Dataset",
    "Original dataset",
    "Time",
    "Latitude",
    "Longitude",
    "Chromosome",
    "Ancestry",
    "Mean Length (bp)",
    "Median Length (bp)",
    "Max Length (bp)",
    "Min Length (bp)",
    "N Fragments",
    "Sequence (bp)",
    "Anc Africa",
    "Anc America",
    "Anc East Asia",
    "Anc Europe",
    "Anc Oceania",
    "Anc South Asia",
  ],
  options_all_sum_stat_frag: ["Individual",
    "Dataset",
    "Original dataset",
    "Region",
    "Population",
    "Chromosome",
    "Haploidy",
    "Start",
    "End",
    "Length",
    "SNPs",
    "Mean Post. Prob.",
    "Ancestry",
    "Admix. Pop. Variants",
    "Altai",
    "Chagyrskaya",
    "Denisova",
    "Vindija"],
  discreteOptions_sum_stat_frag: ["Individual",
    "Dataset",
    "Original dataset",
    "Region",
    "Population",
    "Chromosome",
    "Haploidy",
    "Ancestry",
  ],
  discreteOptions_sum_stat_fragShort: ["ind",
    "dat",
    "oda",
    "reg",
    "pop",
    "chrom",
    "hap",
    "anc",
  ],
  continuousOptions_sum_stat_frag: [
    "Start",
    "End",
    "Length",
    "SNPs",
    "Mean Post. Prob.",
    "Ancestry",
    "Admix. Pop. Variants",
    "Altai",
    "Chagyrskaya",
    "Denisova",
    "Vindija"],
  continuousOptions_sum_stat_fragShort: [
    "start",
    "end",
    "length",
    "snaps",
    "mean_prob",
    "anc",
    "arc",
    "alt",
    "cha",
    "den",
    "vin"],
  discreteOptions: [
    "Sex",
    "Population",
    "Region",
    "Dataset",
    "Original dataset",
    "Chromosome",
    "Ancestry",
  ],
  discreteOptionsShort: ["sex", "pop", "reg", "data", "oda", "chrom", "anc"],
  continuousOptions: [
    "Time",
    "Latitude",
    "Longitude",
    "Mean Length (bp)",
    "Median Length (bp)",
    "Max Length (bp)",
    "Min Length (bp)",
    "N Fragments",
    "Sequence (bp)",
    "Anc Africa",
    "Anc America",
    "Anc East Asia",
    "Anc Europe",
    "Anc Oceania",
    "Anc South Asia",
  ],
  continuousOptionsShort: [
    "tim",
    "lat",
    "lon",
    "len_mea",
    "len_med",
    "len_max",
    "len_min",
    "nfr",
    "seq",
    "ancAFR",
    "ancAMR",
    "ancEAS",
    "ancEUR",
    "ancOCE",
    "ancSAS",
  ],
  mappingToShort: {
    Autosome: "A",
    X: "X",
    "X Prime": "Xprime",
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "den",
    Neanderthal: "Neanderthal",
    Altai: "alt",
    Vindija: "vin",
    Chagyrskaya: "cha",
    AmbigNean: "AmbigNean",
    "Non DAVC": "nonDAVC",
    Individual: "ind",
    Sex: "sex",
    Population: "pop",
    Region: "reg",
    Dataset: "dat",
    "Original dataset": "oda",
    Time: "tim",
    Latitude: "lat",
    Longitude: "lon",
    Chromosome: "chrom",
    Ancestry: "anc",
    "Mean Length (bp)": "len_mea",
    "Median Length (bp)": "len_med",
    "Max Length (bp)": "len_max",
    "Min Length (bp)": "len_min",
    "N Fragments": "nfr",
    "Sequence (bp)": "seq",
    "Anc Africa": "ancAFR",
    "Anc America": "ancAMR",
    "Anc East Asia": "ancEAS",
    "Anc Europe": "ancEUR",
    "Anc Oceania": "ancOCE",
    "Anc South Asia": "ancSAS",
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
    Europe: "EUR",
    MID: "MID",
    "South Asia": "SAS",
    Africa: "AFR",
    "East Asia": "EAS",
    America: "AMR",
    Oceania: "OCE",
    "Central Asia": "CAS",
    Global: "GLOB",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    Joined: "joined",
    Frequency: "freq",
    Shared: "shared",
    Private: "private",
    Haploidy: "hap",
    Start: "start",
    End: "end",
    Length: "length",
    SNPs: "snps",
    "Mean Post. Prob.": "mean_prob",
    "Admix. Pop. Variants": "arc",
  },
  mappingToLong: {
    A: "Autosome",
    X: "X",
    Xprime: "X Prime",
    All: "All",
    Ambiguous: "Ambiguous",
    den: "Denisova",
    Neanderthal: "Neanderthal",
    alt: "Altai",
    vin: "Vindija",
    cha: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    nonDAVC: "Non DAVC",
    ind: "Individual",
    sex: "Sex",
    pop: "Population",
    reg: "Region",
    dat: "Dataset",
    oda: "Original dataset",
    tim: "Time",
    lat: "Latitude",
    lon: "Longitude",
    chrom: "Chromosome",
    anc: "Ancestry",
    len_mea: "Mean Length (bp)",
    len_med: "Median Length (bp)",
    len_max: "Max Length (bp)",
    len_min: "Min Length (bp)",
    nfr: "N Fragments",
    seq: "Sequence (bp)",
    ancAFR: "Anc Africa",
    ancAMR: "Anc America",
    ancEAS: "Anc East Asia",
    ancEUR: "Anc Europe",
    ancOCE: "Anc Oceania",
    ancSAS: "Anc South Asia",
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
    EUR: "Europe",
    MID: "MID",
    SAS: "South Asia",
    AFR: "Africa",
    EAS: "East Asia",
    AMR: "America",
    OCE: "Oceania",
    CAS: "Central Asia",
    GLOB: "Global",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    joined: "Joined",
    freq: "Frequency",
    shared: "Shared",
    private: "Private",
    hap: "Haploidy",
    start: "Start",
    end: "End",
    length: "Length",
    snps: "SNPs",
    mean_prob: "Mean Post. Prob.",
    arc: "Admix. Pop. Variants",
  },
};
