export const datasets = {
  options: [
    "DATA",
    "PDAT",
    "GNOM",
    "PGNO",
    "GENI",
    "PGEN",
    "1KGP",
    "HGDP",
    "SGDP",
    "VANU",
    "IGDP",
    "AYTA",
    "OFAR",
  ],
  mapping: {
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
  },
};

export const chrms_discrete = {
  options: ["Autosome", "X", "X Prime"],
  mapping: {
    Autosome: "A",
    X: "X",
    "X Prime": "Xprime",
  },
};

export const ancestries = {
  options: [
    "All",
    "Ambiguous",
    "Denisova",
    "Neanderthal",
    "Altai",
    "Vindija",
    "Chagyrskaya",
    "AmbigNean",
    "nonDAVC",
  ],
  mapping: {
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    nonDAVC: "nonDAVC",
  },
};

export const bin_marks = [
  { value: 0, label: "0" },
  { value: 25, label: "25" },
  { value: 50, label: "50" },
  { value: 75, label: "75" },
  { value: 100, label: "100" },
];

export const axis = { options: ["Free Axis", "Shared Axis", "Define Range"] };

export const mpp_marks = [
  { value: 0.5, label: "50%" },
  { value: 0.55, label: "" },
  { value: 0.6, label: "" },
  { value: 0.65, label: "65%" },
  { value: 0.7, label: "" },
  { value: 0.75, label: "" },
  { value: 0.8, label: "80%" },
  { value: 0.85, label: "" },
  { value: 0.9, label: "" },
  { value: 0.95, label: "95%" },
];

export const regions = {
  options: [
    "Europe",
    "MID",
    "South Asia",
    "Africa",
    "East Asia",
    "America",
    "Oceania",
    "Central Asia",
  ],
  mapping: {
    Europe: "EUR",
    MID: "MID",
    "South Asia": "SAS",
    Africa: "AFR",
    "East Asia": "EAS",
    America: "AMR",
    Oceania: "OCE",
    "Central Asia": "CAS",
  },
};

export const variables = {
  options_all: [
    "Individual",
    "Sex",
    "Population",
    "Region",
    "Dataset",
    "Oda",
    "Time",
    "Latitude",
    "Longitude",
    "Chromosome",
    "Ancestry",
    "Mean Length (bp)",
    "Median Length (bp)",
    "Max Length (bp)",
    "Min Length (bp)",
    "N Fragments",
    "Sequence (bp)",
    "Anc Africa",
    "Anc America",
    "Anc East Asia",
    "Anc Europe",
    "Anc Oceania",
    "Anc South Asia",
  ],
  discreteOptions: [
    "Sex",
    "Population",
    "Region",
    "Dataset",
    "Oda",
    "Chromosome",
    "Ancestry",
    "reg",
    "sex",
    "pop",
    "data",
    "oda",
    "chrom",
    "anc",
  ],
  discreteOptionsShort: ["sex", "pop", "reg", "data", "oda", "chrom", "anc"],
  continuousOptions: [
    "Time",
    "Latitude",
    "Longitude",
    "Mean Length (bp)",
    "Median Length (bp)",
    "Max Length (bp)",
    "Min Length (bp)",
    "N Fragments",
    "Sequence (bp)",
    "Anc Africa",
    "Anc America",
    "Anc East Asia",
    "Anc Europe",
    "Anc Oceania",
    "Anc South Asia",
  ],
  continuousOptionsShort: [
    "tim",
    "lat",
    "lon",
    "len_mea",
    "len_med",
    "len_max",
    "len_min",
    "nfr",
    "seq",
    "ancAFR",
    "ancAMR",
    "ancEAS",
    "ancEUR",
    "ancOCE",
    "ancSAS",
  ],
  mapping: {
    Autosome: "A",
    X: "X",
    "X Prime": "Xprime",
    All: "All",
    Ambiguous: "Ambiguous",
    Denisova: "Denisova",
    Neanderthal: "Neanderthal",
    Altai: "Altai",
    Vindija: "Vindija",
    Chagyrskaya: "Chagyrskaya",
    AmbigNean: "AmbigNean",
    nonDAVC: "nonDAVC",
    Individual: "ind",
    Sex: "sex",
    Population: "pop",
    Region: "reg",
    Dataset: "dat",
    Oda: "oda",
    Time: "tim",
    Latitude: "lat",
    Longitude: "lon",
    Chromosome: "chrom",
    Ancestry: "anc",
    "Mean Length (bp)": "len_mea",
    "Median Length (bp)": "len_med",
    "Max Length (bp)": "len_max",
    "Min Length (bp)": "len_min",
    "N Fragments": "nfr",
    "Sequence (bp)": "seq",
    "Anc Africa": "ancAFR",
    "Anc America": "ancAMR",
    "Anc East Asia": "ancEAS",
    "Anc Europe": "ancEUR",
    "Anc Oceania": "ancOCE",
    "Anc South Asia": "ancSAS",
    DATA: "DATA",
    PDAT: "PDAT",
    GNOM: "GNOM",
    PGNO: "PGNO",
    GENI: "GENI",
    PGEN: "PGEN",
    "1KGP": "1KGP",
    HGDP: "HGDP",
    SGDP: "SGDP",
    VANU: "VANU",
    IGDP: "IGDP",
    AYTA: "AYTA",
    OFAR: "OFAR",
    Europe: "EUR",
    MID: "MID",
    "South Asia": "SAS",
    Africa: "AFR",
    "East Asia": "EAS",
    America: "AMR",
    Oceania: "OCE",
    "Central Asia": "CAS",
  },
};
